### ISSUE TITLE
Heat map overflows containing div

### ISSUE THREAD

**Issue by theptrk** [patientslikeme/react-calendar-heatmap#25]
Hi, thanks for making this component. Great work! 

I am limiting the days to 100 days but find that the map is really tall on some screens. If I add a max height to the div containing the react component, the heatmap renders below the div. 

Is there a fix for this issue?

Thanks again.

**Comment by iqnivek** [comment]
Yup, I see the issue. Some potential solutions:

**1. Restrict the width instead of the height**

Example:

```
<div style={{ width: 100 }}>
   <CalendarHeatmap {...} />
</div>
```

**2. Make svg equal to height of parent**

Example:

```
# in css
.react-calendar-heatmap {
  height: 100%;
}

# in JSX
<div style={{ height: 100 }}>
  <CalendarHeatmap {...} />
</div>
```

Let me know if this helps, or if you run into any further issues. Thanks!

**Comment by theptrk** [comment]
Thanks!

Is this something you do on your own projects? We could make this a default if it makes sense.

**Comment by iqnivek** [comment]
I usually use grid systems to restrict the width, which works out of the box, and I think that'll be a more common use case since the heatmap is by default horizontally oriented. Since setting height:100% would mess with that, I don't think it should necessarily be a default, unless it turns out a lot of people are restricting height instead of width. But thanks for raising this issue!
